spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: gooweb
  profiles:
    active: dev

logging:
  level:
    root: info
  file: ${spring.application.name}.log

server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/javascript,text/css,text/xml,text/plain
    min-response-size: 2048
  tomcat:
    accept-count: 400
    uri-encoding: utf-8
    min-spare-threads: 25
    max-threads: 400
  connection-timeout: 20000
  servlet-path: /api


---
spring:
  profiles: dev
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.20.4:3306/feijiyuan_chain_operation_dev?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      username: operationAdmin
      password: operationPassword@1234

server:
  port: 9988








  